region: ap-northeast-1

code_deploy:
  - s3_bucket_name: code-deploy-automation
    filepath: hoge/fuga.zip
    application_name: test_20210712
    group_name: blue-green
    cloud_front:
      distribution_id: E1BFT3P6LD2SCL
