source 'https://rubygems.org'

ruby '2.7.4'

group :development, :test do
  gem 'aws-sdk-cloudfront'
  gem 'aws-sdk-codedeploy'
  gem 'aws-sdk-s3'

  gem 'dotenv'

  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
end
